char *parser_error_strs[] = 
{
    "",
    "InternalError: Memory allocation failed",
    "InternalError: Memory reallocation failed",
    "ParserError: Unicode in a variablename",
    "ConversionError: Non numeric char in static number",
    "IndexError: Z Index out of range",
    "IndexError: Y Index out of range",
    "IndexError: X Index out of range",
    "SyntaxError: Unknown comparator",
    "SyntaxError: Index specification without variable name",
    "SyntaxError: end-if without a if head"
    "InternalError: Can not open template file",
    "InternalError: Can not open output file",
    "InternalError: Can not read from template file",
    "TypeError: Too many arguments in macro call",
    "TypeError: Agument missmatch in macro call",
    "InternalError: Error in variable handling",
    "SyntaxError: Missing open bracket",
    "SyntaxError: Missing close bracket",
    "TypeError: Too few arguments in for head",
    "TypeError: Agument missmatch in for head",
    "SyntaxError: Error in for head syntax",
    "ConversionError: Invalid params in range command",
    "NameError: Variable not definied",
    "SyntaxError: Missing \"]\"",
    "SyntaxError: Unexpected token",
    "IndexError: Unsupported index",
    "SyntaxError: Missing command block end",
    "SyntaxError: Macro definition not allowed in for or if block",
    "SyntaxError: Missing \"end-if\"",
    "SyntaxError: Missing \"end-for\"",
    "SyntaxError: Missing 'macro' keyword",
    "SyntaxError: Error in macro head syntax",
    "SyntaxError: Missing \"[\"",
    "SyntaxError: Variable block is empty"
};
